### ISSUE TITLE
TravisCI

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-experiment#12]
I see a [`.travis.yml`](https://github.com/mdn/stumptown-experiment/blob/master/.travis.yml) file but nothing running.

**Comment by peterbe** [comment]
I tried to set it up at https://travis-ci.org/organizations/mdn/repositories but I don't have admin rights to this repo. @wbamberg

**Comment by Elchi3** [comment]
I've enabled this. See the latest PRs that have travis running.
