### ISSUE TITLE
Remove the Python code?

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-experiment#16]
In https://github.com/mdn/stumptown-experiment/pull/14 we're developing the first cli tool that can be used to turn the .md and .yaml files into .json files. 

The next natural thing to do, especially from a kuma perspective, is to now glob for all these .json files and one by one, do a lookup of its recipe and then do something with that. E.g. extract the bits it needs to turn it into kuma content.

So what else do we need Python for. Today, the only entrypoint I see is the `validate.py` script.

Regarding https://github.com/mdn/stumptown-experiment/pull/14 @wbamberg mentioned that that script assumes that the integrity of all the core content (e.g. .md and .yaml files) is perfect. And I think that's right. 

I would be open to rewriting `validate.py` to `validate.js` and reduce this whole project to become a 100% Node project.

**Comment by wbamberg** [comment]
Yes, I think this is a good suggestion.
