### ISSUE TITLE
Change default merge to "squash and merge"

### ISSUE THREAD

**Issue by ddbeck** [mdn/stumptown-experiment#52]
There was a discussion recently that squash and merge is preferred for MDN projects.

Someone with admin rights on this repo (@wbamberg?) ought to turn off the other merge options in the repository settings. See [Configuring commit squashing for pull requests](https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests) for instructions.

**Comment by escattone** [comment]
Saw this request in my email, so thought I'd go ahead and do it since I've done the same on Kuma.

**Comment by ddbeck** [comment]
Thank you, @escattone!
